### ISSUE TITLE
Release to maven central?

### ISSUE THREAD

**Issue by TheSnoozer** [etiennestuder/java-ordered-properties#3]
Hello,
thank you for this great project!
I was wondering if you plan to release this to maven central.
At least in my perspective maven users might not have a `bintray` repository declared.

Use-case:
https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/284
https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/472

Thank you :-)

**Comment by etiennestuder** [comment]
Good idea. Done. Thanks.

https://oss.sonatype.org/#nexus-search;quick~nu.studer
