### ISSUE TITLE
Add support for preserving comment lines

### ISSUE THREAD

**Issue by theangrydev** [etiennestuder/java-ordered-properties#39]
Sometimes there are human readable comment lines written to property files like:

```
#
# some human readable text
#
some.key=some.value
```

These appear to be tolerated well when reading a properties file, but are lost when writing a properties file

Can you add support for this?

**Comment by Spacelord09** [comment]
I think this is a dupe of #6

**Comment by theangrydev** [comment]
Ok, I ended up using https://commons.apache.org/proper/commons-configuration/userguide/howto_properties.html and might try https://github.com/hupfdule/apron as referenced in #6
