### ISSUE TITLE
Illegal reflective access in JDK11

### ISSUE THREAD

**Issue by dfa1** [etiennestuder/java-ordered-properties#5]
Hello :-) 

When I run git-commit-id-plugin on JDK11 I get this warning:

```
[INFO] --- git-commit-id-plugin:4.0.1:revision (fetch-git-revision) @ hosh-runtime ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nu.studer.java.util.OrderedProperties (file:/Users/dfa/.m2/repository/nu/studer/java-ordered-properties/1.0.4/java-ordered-properties-1.0.4.jar) to method java.util.Properties.store0(java.io.BufferedWriter,java.lang.String,boolean)
WARNING: Please consider reporting this to the maintainers of nu.studer.java.util.OrderedProperties
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by etiennestuder** [comment]
Yes, if you have characters in your properties/comments that need escaping (see [here](https://github.com/etiennestuder/java-ordered-properties/blob/bbe7bf35126250d5caafa870f09d4290886d8224/src/main/java/nu/studer/java/util/OrderedProperties.java#L192)), then the code needs to resort to reflection to reuse the logic of the JDK Properties class.

Alternatively, you can use the API `OrderedProperties#store(java.io.Writer, java.lang.String)` which will never have to resort to reflection.
