### ISSUE TITLE
Allow comments between the properties.

### ISSUE THREAD

**Issue by Spacelord09** [etiennestuder/java-ordered-properties#6]
Hey great work!

is it posible to implement a method to allow writing of comments between the properties?
Example:

(for better understanding i added a linebreak between the properties and comments.)
```
# imap, imaps (UNSUPPORTED: pop3)
protocol=imaps

# your mailserver
host=example.com

# protocol port
port=993

# your username
userName=user

# YourSecretPassword
password=password

# folder to be worked on.
mail_source_folder=INBOX

# if done move mail to.
mail_destination_folder=DONE

# allowMailfrom = Only allow mail from the following addresses.
allowMailfrom=user@example.com

# path_prefix= Prefix to the folder structure path.
path_prefix=./
```

**Comment by etiennestuder** [comment]
Thanks for the request. I do not intend to make any functional enhancements to this class due to time-constraints and also because I would like this project to remain very focussed. I _think_ there are libraries out there that will allow to read/write properties files while preserving the structure of comments, too.

**Comment by Spacelord09** [comment]
Thanks for the explanation.
what should i watch out for if i want to implement this myself in a fork of your project?

**Comment by etiennestuder** [comment]
@Spacelord09 not sure. A key feature of this project is to reuse the JDK logic instead of reimplementing it. If you deviate from this by implementing the reading/writing logic yourself, you might first want to look at other projects that already provide this functionality out of the box.

**Comment by Spacelord09** [comment]
Hey I found this: https://github.com/hupfdule/apron
I'll try it out in the next days.
